Entity/ContentPage.php
<?php

namespace Webberig\CMSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Locale\Exception\NotImplementedException;

/**
 * ContentPages
 *
 * @ORM\Table(name="content_pages")
 * @ORM\Entity
 */
class ContentPage
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="Language", inversedBy="pages")
     * @ORM\JoinColumn(name="language", referencedColumnName="id", nullable=false)
     */
    private $language;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="ContentCategory", inversedBy="pages")
     * @ORM\JoinColumn(name="category", referencedColumnName="id", nullable=false)
     */
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="intro", type="text", nullable=true)
     */
    private $intro;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=true)
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startDate", type="date", nullable=true)
     */
    private $startdate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="stopDate", type="date", nullable=true)
     */
    private $stopdate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="itemDate", type="date", nullable=true)
     */
    private $itemdate;

    /**
     * @var string
     *
     * @ORM\Column(name="subtitle1", type="string", length=255, nullable=true)
     */
    private $subtitle1;

    /**
     * @var string
     *
     * @ORM\Column(name="subtitle2", type="string", length=255, nullable=true)
     */
    private $subtitle2;

    /**
     * @var integer
     *
     * @ORM\Column(name="parentID", type="integer", nullable=true)
     */
    private $parentid;

    /**
     * @var string
     *
     * @ORM\Column(name="modifiedBy", type="string", length=45, nullable=true)
     */
    private $modifiedby;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean", nullable=false)
     */
    private $active;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="modifiedDate", type="date", nullable=true)
     */
    private $modifieddate;



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set language
     *
     * @param integer $language
     * @return ContentPages
     */
    public function setLanguage($language)
    {
        $this->language = $language;
    
        return $this;
    }

    /**
     * Get language
     *
     * @return integer 
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return ContentPages
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return ContentPages
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set intro
     *
     * @param string $intro
     * @return ContentPages
     */
    public function setIntro($intro)
    {
        $this->intro = $intro;
    
        return $this;
    }

    /**
     * Get intro
     *
     * @return string 
     */
    public function getIntro()
    {
        return $this->intro;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return ContentPages
     */
    public function setContent($content)
    {
        $this->content = $content;
    
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return ContentPages
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set startdate
     *
     * @param \DateTime $startdate
     * @return ContentPages
     */
    public function setStartdate($startdate)
    {
        $date = new \DateTime();
        $date = $date->createFromFormat("d/m/Y", $startdate);
        if ($date === false)
            throw new \Exception("Unable to parse startdate");
        $this->startdate = $date;

        return $this;
    }

    /**
     * Get startdate
     *
     * @return \DateTime 
     */
    public function getStartdate()
    {
        return $this->startdate;
    }

    /**
     * Set stopdate
     *
     * @param \DateTime $stopdate
     * @return ContentPages
     */
    public function setStopdate($stopdate)
    {
        $date = new \DateTime();
        $date = $date->createFromFormat("d/m/Y", $stopdate);
        if ($date === false)
            throw new \Exception("Unable to parse stopdate");
        $this->stopdate = $date;

        return $this;
    }

    /**
     * Get stopdate
     *
     * @return \DateTime 
     */
    public function getStopdate()
    {
        return $this->stopdate;
    }

    /**
     * Set itemdate
     *
     * @param \DateTime $itemdate
     * @return ContentPages
     */
    public function setItemdate($itemdate)
    {
        $date = new \DateTime();
        $date = $date->createFromFormat("d/m/Y", $itemdate);
        if ($date === false)
            throw new \Exception("Unable to parse itemdate");
        $this->itemdate = $date;
    
        return $this;
    }

    /**
     * Get itemdate
     *
     * @return \DateTime 
     */
    public function getItemdate()
    {
        return $this->itemdate;
    }

    /**
     * Set subtitle1
     *
     * @param string $subtitle1
     * @return ContentPages
     */
    public function setSubtitle1($subtitle1)
    {
        $this->subtitle1 = $subtitle1;
    
        return $this;
    }

    /**
     * Get subtitle1
     *
     * @return string 
     */
    public function getSubtitle1()
    {
        return $this->subtitle1;
    }

    /**
     * Set subtitle2
     *
     * @param string $subtitle2
     * @return ContentPages
     */
    public function setSubtitle2($subtitle2)
    {
        $this->subtitle2 = $subtitle2;
    
        return $this;
    }

    /**
     * Get subtitle2
     *
     * @return string 
     */
    public function getSubtitle2()
    {
        return $this->subtitle2;
    }

    /**
     * Set parentid
     *
     * @param integer $parentid
     * @return ContentPages
     */
    public function setParentid($parentid)
    {
        $this->parentid = $parentid;
    
        return $this;
    }

    /**
     * Get parentid
     *
     * @return integer 
     */
    public function getParentid()
    {
        return $this->parentid;
    }

    /**
     * Set modifiedby
     *
     * @param string $modifiedby
     * @return ContentPages
     */
    public function setModifiedby($modifiedby)
    {
        $this->modifiedby = $modifiedby;
    
        return $this;
    }

    /**
     * Get modifiedby
     *
     * @return string 
     */
    public function getModifiedby()
    {
        return $this->modifiedby;
    }

    /**
     * Set modifieddate
     *
     * @param \DateTime $modifieddate
     * @return ContentPages
     */
    public function setModifieddate($modifieddate)
    {
        $this->modifieddate = $modifieddate;
    
        return $this;
    }

    /**
     * Get modifieddate
     *
     * @return \DateTime 
     */
    public function getModifieddate()
    {
        return $this->modifieddate;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return ContentPage
     */
    public function setActive($active)
    {
        $this->active = $active;
    
        return $this;
    }

    /**
     * Get active
     *
     * @return boolean 
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set category
     *
     * @param \Webberig\CMSBundle\Entity\ContentCategory $category
     * @return ContentPage
     */
    public function setCategory(\Webberig\CMSBundle\Entity\ContentCategory $category)
    {
        $this->category = $category;
    
        return $this;
    }

    /**
     * Get category
     *
     * @return \Webberig\CMSBundle\Entity\ContentCategory 
     */
    public function getCategory()
    {
        return $this->category;
    }

    public function getFullUrl()
    {
        if (!$this->getCategory()->getUseurl())
            throw new \Exception("De categorie van deze pagina bevat geen URL's");
        $url = $this->getLanguage()->getAbbreviation() . "/";

        $category_slug = $this->getCategory()->getUrlprefix();
        if (!empty($category_slug))
            $url .= $category_slug . "/";

        $url .= $this->getUrl();
        return $url;
    }

    public function isPublic() {
        $now = new \DateTime();
        if ($this->getActive() == false) {

Controller/ContentController.php
<?php

namespace Webberig\CMSBundle\Controller;

use Gregwar\Image\Image;
use Gregwar\ImageBundle\Services\ImageHandling;
use Symfony\Component\HttpFoundation\JsonResponse;
use Webberig\CMSBundle\Entity\ContentPage;

class ContentController extends BaseController
{
    public function indexAction()
    {
        $language = $this->getLanguageService()->getFirst();
        $category = $this->getCategoryService()->getFirst();

        return $this->redirect($this->generateUrl("webberig_cms_content_list", array("category" => $category->getSlug(), "language" => $language->getAbbreviation())));
    }

    public function categoryIndexAction($category)
    {
        $cat = $this->getCategory($category);
        $language = $this->getLanguageService()->getFirst();

        return $this->redirect($this->generateUrl("webberig_cms_content_list", array("category" => $cat->getSlug(), "language" => $language->getAbbreviation())));
    }

    public function listAction($category, $language)
    {
        $cat = $this->getCategory($category);
        $lang = $this->getLanguage($language);

        $pages = $this->getPageService()->getList($lang->getId(), $cat->getId());

        return $this->render('WebberigCMSBundle:Content:list.html.twig', array("pages" => $pages, "category" => $cat, "language" => $lang, "languages" => $this->getLanguageService()->getList()));
    }

    public function pageEditAction($category, $page)
    {
        $cat = $this->getCategory($category);

        $p = $this->getPage($page);
        if ($p->getCategory()->getId() != $p->getId())
            $this->createNotFoundException('Page not found - Page category does not match URL category');

        $gallery = $this->getPageService()->getGallery($p);

        return $this->render('WebberigCMSBundle:Content:pageEdit.html.twig',
            array(
                "category" => $cat,
                "page" => $p,
                "language" => $p->getLanguage(),
                "gallery" => $gallery
            ));

    }

    public function newAction($category, $language)
    {
        $cat = $this->getCategory($category);
        $lang = $this->getLanguage($language);

        $page = new \Webberig\CMSBundle\Entity\ContentPage();
        $page->setActive(true);

        return $this->render('WebberigCMSBundle:Content:pageEdit.html.twig',
            array(
                "category" => $cat,
                "language" => $lang,
                "page" => $page
            ));

    }

    public function pageSaveAction($category, $page)
    {
        /** @var $pageService \Webberig\CMSBundle\Service\ContentPage */
        $pageService = $this->get('cms.contentpage');

        $p = $this->getPage($page);
        $cat = $this->getCategory($category);

        $request = $this->getRequest()->request;
        $post = $request->all();


        $p = $pageService->populate($post, $p);
        $pageService->save($p);

        $this->getPage($page);

        $this->addFlashSuccess("De pagina is bewaard.");
        return $this->redirect($this->generateUrl("webberig_cms_content_list", array("category" => $category, "language" => $p->getLanguage()->getAbbreviation())));
    }

    public function newPageSaveAction($category, $language)
    {
         /*
         * @var $pageService \Webberig\CMSBundle\Service\ContentPage
         * @var $langService \Webberig\CMSBundle\Service\Language
         */
        $pageService = $this->get('cms.contentpage');
        $langService = $this->get('cms.language');

        // Request
        $request = $this->getRequest()->request;
        $post = $request->all();

        $cat = $this->getCategory($category);
        $lang = $this->getLanguage($language);


        $page = new \Webberig\CMSBundle\Entity\ContentPage();
        $page = $pageService->populate($post, $page);
        $page
            ->setLanguage($lang)
            ->setCategory($cat);
        $pageService->save($page);
        $this->addFlashSuccess("De pagina is toegevoegd.");


        return $this->redirect($this->generateUrl("webberig_cms_content_list", array("category" => $category, "language" => $lang->getAbbreviation())));
    }

    public function deletePhotoAction ($category, $language, $page, $img) {
        $category = $this->getCategory($category);
        $language = $this->getLanguage($language);
        $page = $this->getPage($page);

        $folder = "uploads/gallery/" . $page->getId() . "/";

        if (!is_dir($folder)) {
            mkdir($folder);
        }
        $filename = $folder . $img;
        unlink($filename);

        return new JsonResponse(array(
            "success" => true
        ));
    }

    public function uploadPhotoAction ($category, $language, $page)
    {
        $category = $this->getCategory($category);
        $language = $this->getLanguage($language);
        $page = $this->getPage($page);

        /**
         * @var $file \Symfony\Component\HttpFoundation\File\UploadedFile
         */
        $filebag = $this->getRequest()->files->all();
        $file = $filebag["files"][0];
        if (!is_object($file)) {
            return new JsonResponse(array(
                "success" => false,
                "message" => "Geen files gevonden"
            ));
        }

        $image = new Image($file->getRealPath());

        try {
            if ($image->width() > 1200 || $image->height() > 1200) {
                $image = $image->cropResize(1200,1200);
            }

        } catch(\Exception $e) {
            return new JsonResponse(array(
                "success" => false,
                "message" => "Opgeladen bestand is geen geldige afbeelding: " . $e->getMessage()
            ));
        }


        //$folder = $this->getRequest()->server->get('DOCUMENT_ROOT');
        $folder = "uploads/gallery/" . $page->getId() . "/";

        if (!is_dir($folder)) {
            mkdir($folder);
        }
        $filename = $folder . $file->getClientOriginalName();

        if (is_file($filename)) {
            return new JsonResponse(array(
                "success" => false,
                "message" => "Bestand bestaat reeds"
            ));
        }
        $image->save($filename);

        /**
         * @var $imageHandler ImageHandling
         */
        $image->setCacheDir("cache");
        $url = $image->zoomCrop(200,200)->jpeg();

        return new JsonResponse(array(
            "success" => true,
            "url" => $url
        ));

    }

    protected function getCategory($id)
    {
        $cat = parent::getCategory($id);
        \Webberig\BackendBundle\Service\Menu::singleton()->setActive("content_" . $id);
        return $cat;
    }

    /**
     * @param $id
     * @return ContentPage
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    private function getPage($id)
    {
        $page = $this->getPageService()->getById($id);
        if ($page==null)
            throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException("Pagina niet gevonden");

        return $page;
    }

    public function deleteAction($category, $language, $page) {
        $page = $this->getPageService()->getById($page);
        $this->getPageService()->deletePage($page);
        $lang = $this->getLanguage($language);
        $this->addFlashSuccess("De pagina is verwijderd.");


        return $this->redirect($this->generateUrl("webberig_cms_content_list", array("category" => $category, "language" => $lang->getAbbreviation())));

    }
}

Resources/views/Content/list.html.twig
{% extends 'WebberigBackendBundle:_Layouts:main.html.twig' %}
{% import 'WebberigSharedBundle:Macros:Buttons.html.twig' as Button %}

{% block pagetitle category.name %}

{% block pageheader %}
    <h1>{{ category.name }}</h1>
    <ul class="breadcrumb">
        <li>Site content</li>
        <li class="active">{{ category.name }}</li>
    </ul>
    <div class="buttons">
        {{ Button.LinkInfo('Nieuw item', path('webberig_cms_content_new', {category: category.slug, language: language.abbreviation}), '', 'glyphicon-plus') }}
        {% if languages|length > 1 %}
        <div class="btn-group">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
                {{ language.name }}
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right">
                {% for item in languages %}
                    {% if item.id != language.id %}
                        <li><a href="{{ path('webberig_cms_content_list', {category: category.slug, language: item.abbreviation}) }}">{{ item.name }}</a></li>
                    {% endif %}
                {% endfor %}
                <!-- dropdown menu links -->
            </ul>
        </div>
        {% endif %}
    </div>
{% endblock %}
{% block body %}


    <table class="table table-striped" id="tblUsers">
        <thead>
            <tr>
                <th>Naam</th>
                {% if category.useUrl %}
                    <th>URL</th>
                {% endif %}
                {% if category.usedate %}
                    <th>Datum</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for page in pages %}
            <tr>
                <td><a href="{{ path('webberig_cms_content_edit', {category: category.slug, language: language.abbreviation, page: page.id}) }}">{{ page.title }}</a></td>
                {% if category.useUrl %}
                    <td><a href="{{ path('webberig_cms_content_edit', {category: category.slug, language: language.abbreviation, page: page.id}) }}">{{ page.fullUrl }}</a></td>
                {% endif %}
                {% if category.usedate %}
                    <td>{{ page.itemDate|date('d/m/Y') }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

Resources/views/Content/pageEdit.html.twig
{% extends 'WebberigBackendBundle:_Layouts:main.html.twig' %}
{% import 'WebberigSharedBundle:Macros:Buttons.html.twig' as Button %}

{% block pagetitle  %}
    {% if page.id is not empty %}{{ page.title }}{% else %}Nieuw item{% endif %}
{% endblock %}
{% block pageheader %}
    <h1>{% if page.id is not empty %}{{ page.title }}{% else %}Nieuw item{% endif %}</h1>
    <ul class="breadcrumb">
        <li>Site content</li>
        <li><a href="{{ path('webberig_cms_content_list', {category: category.slug, language: language.abbreviation}) }}">{{ category.name }}</a></li>
        <li class="active">{% if page.id is not empty %}{{ page.title }}{% else %}Nieuwe pagina{% endif %}</li>
    </ul>
    <div class="buttons">

    </div>
{% endblock %}

{% block body %}

    {% set formId = 'frmPageEdit' %}
    <form method="POST">
        <div class="row">
            <div class="col-sm-6">
                <fieldset>
                    <legend>Algemeen</legend>
                    {{ 'title'|fText({label: 'Titel',value: page.title, formId: formId}) }}
                    {% if category.useURL %}
                        {{ 'url'|fText({label: 'URL', value: page.url, formId: formId}) }}
                    {% endif %}
                    {% if category.useSubtitle1 %}
                        {{ 'subtitle1'|fText({label: category.subtitle1Label, value: page.subtitle1, formId: formId}) }}
                    {% endif %}
                    {% if category.useSubtitle2 %}
                        {{ 'subtitle1'|fText({label: category.subtitle2Label, value: page.subtitle2, formId: formId}) }}
                    {% endif %}
                    {{ 'active'|fCheckbox({label: 'Actief',value: page.active, formId: formId}) }}
                </fieldset>
            </div>
            <div class="col-sm-6">
                {% if category.useMETA %}
                    <fieldset>
                        <legend>META</legend>
                        {{ 'description'|fText({value: page.description, label: 'Description', formId: formId}) }}
                    </fieldset>
                {% endif %}
                {% if category.useDate or category.useDateRange %}
                    <fieldset>
                        <legend>Periode</legend>
                        {% if category.useDate %}
                            {{ 'itemdate'|fDate({value: page.itemdate|date('d/m/Y'), label: 'Publicatiedatum', formId: formId}) }}
                        {% endif %}
                        {% if category.useDateRange %}
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ 'startdate'|fDate({value: page.startdate|date('d/m/Y'), label: 'Startdatum', formId: formId}) }}
                                </div>
                                <div class="col-lg-6">
                                {{ 'stopdate'|fDate({value: page.stopdate|date('d/m/Y'), label: 'Einddatum', formId: formId}) }}
                                </div>
                            </div>
                        {% endif %}
                    </fieldset>
                {% endif %}

            </div>
        </div>
        {% if category.useIntro %}
        <fieldset>
            <legend>Introductie</legend>
            {{ 'intro'|fWysiwyg({value: page.intro, formId: formId}) }}
            <br />
        </fieldset>
        {% endif %}
        {% if category.useContent %}
        <fieldset>
            <legend>Inhoud</legend>
            {{ 'content'|fWysiwyg({value: page.content, formId: formId}) }}
            <br />
        </fieldset>
        {% endif %}


        {% if category.useGallery and page.id is not empty %}
            <div class="cms-gallery">
                <legend><span class="btn btn-info btn-xs pull-right">
                                    <i class="glyphicon glyphicon-plus"></i> Foto's toevoegen
                                    <input type="file" class="upload" name="files[]" multiple="" data-url="{{ path('webberig_cms_content_upload', {category: category.slug, language: language.abbreviation, page: page.id }) }}">
                                </span>Foto's
                </legend>
                {#
                <div class="dropzone">
                    Sleep hier foto's om ze toe te voegen...
                </div>
                #}
                <div class="items">

                    {% for img in gallery %}
                        <div class="item">
                            <img src="{{ image(img).zoomCrop(200,200) }}" />
                            <button type="button" data-url="{{ path('webberig_cms_content_image_delete', {category: category.slug, language: language.abbreviation, page: page.id, img: img|split('/')|last }) }}" class="btn btn-danger btn-xs delete"><i class="glyphicon glyphicon-trash"></i></button>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="form-actions">
            {% if page.id is not empty %}
                {{ Button.LinkDanger('Verwijderen', path('webberig_cms_content_delete', {category: category.slug, language: language.abbreviation, page: page.id}), formId ~ '-Delete', 'icon-remove') }}
            {% endif %}
            {{ Button.Submit() }}
        </div>


    </form>

{% endblock %}
{% block javascripts %}
    {% include 'WebberigCKEditorBundle:Configs:ckeditor.html.twig' %}
    <script>
        $(".cms-gallery").on("click", ".delete", function() {
            var $this = $(this),
                item = $this.closest(".item");

            item.slideUp();
            $.ajax({
                url: $this.data("url")
            }).done(function() {
                item.remove();
            }).fail(function() {
                item.slideDown();
            });
        })

    </script>
{% endblock %}